/* Cyclical vs Defensive Ratio Dashboard
   - Reads ETF history from a local CSV file generated by the updater script.
   - Intended for static hosting after a scheduled daily data refresh.
*/

const CYCLICAL = [
  { ticker: "XLI", name: "Industrials" },
  { ticker: "XLB", name: "Materials" },
  { ticker: "XLY", name: "Consumer Discretionary" },
  { ticker: "XLE", name: "Energy" },
  { ticker: "XLF", name: "Financials" }
];

const DEFENSIVE = [
  { ticker: "XLP", name: "Consumer Staples" },
  { ticker: "XLV", name: "Healthcare" },
  { ticker: "XLU", name: "Utilities" },
  { ticker: "GLD", name: "Gold" }
];

const CHECKS = [
  { id: "xlf_lag", label: "Financials lagging: XLF underperforms S&P 500 (manual)", weight: 1 },
  { id: "yc_warn", label: "Yield curve warning: 2y/10y inversion or flattening (manual)", weight: 1 },
  { id: "credit", label: "Credit spreads widening: High yield spread rising (manual)", weight: 1 },
  { id: "breadth", label: "Market breadth declining: % above 50DMA falling (manual)", weight: 1 },
  { id: "macro", label: "Macro weakness: PMI / confidence deteriorating (manual)", weight: 1 }
];

const CSV_PATH = "./data/etf_prices.csv";
const ALL_ETFS = [...CYCLICAL, ...DEFENSIVE];
const ETF_LOOKUP = new Map(ALL_ETFS.map((item) => [item.ticker, item]));

const LS = {
  get(key, fallback = null) {
    try {
      const value = localStorage.getItem(key);
      return value ? JSON.parse(value) : fallback;
    } catch {
      return fallback;
    }
  },
  set(key, value) {
    localStorage.setItem(key, JSON.stringify(value));
  }
};

function fmt(n, digits = 2) {
  if (n === null || n === undefined || Number.isNaN(n)) return "-";
  return Number(n).toFixed(digits);
}

function pct(n, digits = 2) {
  if (n === null || n === undefined || Number.isNaN(n)) return "-";
  return (n * 100).toFixed(digits);
}

function normalizeTo100(series, startDate = null) {
  const filtered = startDate ? series.filter((point) => point.date >= startDate) : series.slice();
  if (filtered.length < 2) return [];
  const base = filtered[0].close;
  return filtered.map((point) => ({ date: point.date, v: (point.close / base) * 100 }));
}

function intersectDates(seriesList) {
  const sets = seriesList.map((series) => new Set(series.map((point) => point.date)));
  const base = [...sets[0]];
  return base.filter((date) => sets.every((set) => set.has(date))).sort();
}

function averageBasket(normSeriesList, commonDates) {
  const mapList = normSeriesList.map((series) => new Map(series.map((point) => [point.date, point.v])));
  return commonDates.map((date) => {
    const values = mapList.map((map) => map.get(date)).filter((value) => Number.isFinite(value));
    const average = values.reduce((sum, value) => sum + value, 0) / values.length;
    return { date, v: average };
  });
}

function movingAverage(values, window) {
  const out = [];
  for (let index = 0; index < values.length; index += 1) {
    const start = Math.max(0, index - window + 1);
    const slice = values.slice(start, index + 1);
    const average = slice.reduce((sum, value) => sum + value, 0) / slice.length;
    out.push(average);
  }
  return out;
}

function slope(values, k = 20) {
  if (values.length < 5) return 0;
  const n = Math.min(k, values.length);
  const y = values.slice(values.length - n);
  const x = [...Array(n).keys()];
  const xMean = (n - 1) / 2;
  const yMean = y.reduce((sum, value) => sum + value, 0) / n;
  let numerator = 0;
  let denominator = 0;

  for (let index = 0; index < n; index += 1) {
    numerator += (x[index] - xMean) * (y[index] - yMean);
    denominator += (x[index] - xMean) * (x[index] - xMean);
  }

  return denominator === 0 ? 0 : numerator / denominator;
}

function returnOver(series, days) {
  if (!series || series.length < days + 1) return null;
  const last = series[series.length - 1].close;
  const prior = series[Math.max(0, series.length - 1 - days)].close;
  return prior ? (last / prior) - 1 : null;
}

function parseCsvLine(line) {
  const out = [];
  let value = "";
  let inQuotes = false;

  for (let index = 0; index < line.length; index += 1) {
    const char = line[index];
    const next = line[index + 1];

    if (char === "\"") {
      if (inQuotes && next === "\"") {
        value += "\"";
        index += 1;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === "," && !inQuotes) {
      out.push(value);
      value = "";
    } else {
      value += char;
    }
  }

  out.push(value);
  return out;
}

function parseCsv(text) {
  const lines = text.split(/\r?\n/).filter((line) => line.trim().length > 0);
  if (lines.length < 2) {
    throw new Error("CSV file is empty. Run the updater script first.");
  }

  const headers = parseCsvLine(lines[0]).map((header) => header.trim());
  const rows = [];

  for (const line of lines.slice(1)) {
    const values = parseCsvLine(line);
    const row = {};
    headers.forEach((header, index) => {
      row[header] = values[index] ?? "";
    });
    rows.push(row);
  }

  return rows;
}

async function loadSeriesFromCsv() {
  const url = `${CSV_PATH}?ts=${Date.now()}`;
  const response = await fetch(url, { cache: "no-store" });
  if (!response.ok) {
    throw new Error(`Could not load ${CSV_PATH}. Generate the CSV first.`);
  }

  const csvText = await response.text();
  const rows = parseCsv(csvText);
  const grouped = new Map();

  for (const row of rows) {
    const ticker = (row.ticker || "").trim().toUpperCase();
    const date = (row.date || "").trim();
    const close = Number(row.close);
    if (!ETF_LOOKUP.has(ticker) || !date || !Number.isFinite(close)) continue;

    if (!grouped.has(ticker)) grouped.set(ticker, []);
    grouped.get(ticker).push({ date, close });
  }

  const results = ALL_ETFS.map((etf) => ({
    ticker: etf.ticker,
    name: etf.name,
    series: (grouped.get(etf.ticker) || []).sort((a, b) => a.date.localeCompare(b.date))
  }));

  const missing = results.filter((item) => item.series.length < 30).map((item) => item.ticker);
  if (missing.length) {
    throw new Error(`CSV is missing enough history for: ${missing.join(", ")}`);
  }

  const maxDate = rows.reduce((latest, row) => {
    const date = (row.date || "").trim();
    return date > latest ? date : latest;
  }, "");

  const generatedAt = rows[0]?.generated_at_utc || "";
  return { results, asof: maxDate, generatedAt };
}

let chart = null;

function setBuildInfo() {
  const el = document.getElementById("buildDate");
  el.textContent = new Date().toISOString().replace("T", " ").slice(0, 19) + "Z";
}

function renderChecklist() {
  const root = document.getElementById("checklist");
  root.innerHTML = "";

  CHECKS.forEach((check) => {
    const saved = !!LS.get(`check_${check.id}`, false);
    const div = document.createElement("div");
    div.className = "check";
    div.innerHTML = `
      <input type="checkbox" id="chk_${check.id}" ${saved ? "checked" : ""}/>
      <div>
        <div>${check.label}</div>
        <div class="small">Stored locally in your browser.</div>
      </div>
    `;

    root.appendChild(div);
    div.querySelector("input").addEventListener("change", (event) => {
      LS.set(`check_${check.id}`, !!event.target.checked);
      updateSignalsUI();
    });
  });

  updateSignalsUI();
}

function updateSignalsUI() {
  let count = 0;
  CHECKS.forEach((check) => {
    if (LS.get(`check_${check.id}`, false)) count += check.weight;
  });

  document.getElementById("signalsCount").textContent = String(count);
  document.getElementById("stance").textContent =
    count >= 3 ? "Defensive bias" : (count === 2 ? "Neutral / watch" : "Risk-on ok");
}

function setStatus(kind, text, cacheInfo = "") {
  const dot = document.getElementById("statusDot");
  dot.className = `dot ${kind || "ok"}`;
  document.getElementById("statusText").textContent = text;
  document.getElementById("cacheInfo").textContent = cacheInfo || "CSV: -";
}

function setBadge(kind, text) {
  const badge = document.getElementById("ratioBadge");
  const color = kind === "bad" ? "#7f1d1d" : (kind === "warn" ? "#78350f" : "#064e3b");
  badge.style.borderColor = "#334155";
  badge.style.background = color;
  badge.style.color = "#e5e7eb";
  badge.textContent = `Status: ${text}`;
}

function renderTable(rows) {
  const body = document.getElementById("tblBody");
  body.innerHTML = "";

  rows.forEach((row) => {
    const tr = document.createElement("tr");
    tr.innerHTML = `
      <td class="mono" title="${row.name}">${row.ticker}</td>
      <td>${fmt(row.last, 2)}</td>
      <td>${row.r1w === null ? "-" : pct(row.r1w, 2)}</td>
      <td>${row.r1m === null ? "-" : pct(row.r1m, 2)}</td>
      <td>${row.r3m === null ? "-" : pct(row.r3m, 2)}</td>
    `;
    body.appendChild(tr);
  });
}

function makeChart(labels, ratio, ratioMA) {
  const ctx = document.getElementById("ratioChart").getContext("2d");
  if (chart) chart.destroy();

  chart = new Chart(ctx, {
    type: "line",
    data: {
      labels,
      datasets: [
        { label: "Growth Ratio", data: ratio, borderWidth: 2, tension: 0.25, pointRadius: 0 },
        { label: "MA", data: ratioMA, borderWidth: 1, tension: 0.25, pointRadius: 0 }
      ]
    },
    options: {
      responsive: true,
      plugins: {
        legend: { labels: { color: "#cbd5e1" } },
        tooltip: { mode: "index", intersect: false }
      },
      scales: {
        x: { ticks: { color: "#94a3b8", maxTicksLimit: 8 }, grid: { color: "rgba(148,163,184,0.12)" } },
        y: { ticks: { color: "#94a3b8" }, grid: { color: "rgba(148,163,184,0.12)" } }
      }
    }
  });
}

async function runFromCsv() {
  const smoothing = Number(document.getElementById("smooth").value);
  const startOverride = document.getElementById("startDate").value || null;
  setStatus("ok", "Loading CSV data...", "CSV: reading file");

  const { results, asof, generatedAt } = await loadSeriesFromCsv();
  const cyc = results.filter((row) => CYCLICAL.some((item) => item.ticker === row.ticker));
  const def = results.filter((row) => DEFENSIVE.some((item) => item.ticker === row.ticker));

  const cycNorm = cyc.map((row) => ({ ticker: row.ticker, name: row.name, norm: normalizeTo100(row.series, startOverride) }));
  const defNorm = def.map((row) => ({ ticker: row.ticker, name: row.name, norm: normalizeTo100(row.series, startOverride) }));

  const cycDates = intersectDates(cycNorm.map((row) => row.norm));
  const defDates = intersectDates(defNorm.map((row) => row.norm));
  const common = cycDates.filter((date) => defDates.includes(date));

  if (common.length < 30) {
    throw new Error("Not enough overlapping history in the CSV. Try an earlier start date.");
  }

  const cycIndex = averageBasket(cycNorm.map((row) => row.norm), common);
  const defIndex = averageBasket(defNorm.map((row) => row.norm), common);

  const ratio = common.map((date, index) => cycIndex[index].v / defIndex[index].v);
  const ratioSmooth = smoothing > 1 ? movingAverage(ratio, smoothing) : ratio.slice();
  const ratioMA = movingAverage(ratioSmooth, 20);

  const last = ratioSmooth[ratioSmooth.length - 1];
  const lastMA = ratioMA[ratioMA.length - 1];
  const sl = slope(ratioSmooth, 25);
  const down = last < lastMA && sl < 0;
  const severe = down && (last < ratioMA[Math.max(0, ratioMA.length - 40)]);

  if (severe) setBadge("bad", "Persistent defensive rotation");
  else if (down) setBadge("warn", "Ratio weakening");
  else setBadge("ok", "Cyclicals leading / stable");

  makeChart(common, ratioSmooth, ratioMA);

  const rows = results.map((row) => ({
    ticker: row.ticker,
    name: row.name,
    last: row.series[row.series.length - 1]?.close ?? null,
    r1w: returnOver(row.series, 5),
    r1m: returnOver(row.series, 21),
    r3m: returnOver(row.series, 63)
  })).sort((a, b) => a.ticker.localeCompare(b.ticker));

  renderTable(rows);

  const cacheInfo = generatedAt
    ? `CSV: through ${asof} | built ${generatedAt}`
    : `CSV: through ${asof}`;

  setStatus(
    severe ? "bad" : (down ? "warn" : "ok"),
    severe
      ? "Ratio has been weakening with negative slope. Treat as a real scare candidate if other signals confirm."
      : (down ? "Ratio weakening. Watch for persistence plus a larger signal cluster." : "Ratio stable or strengthening."),
    cacheInfo
  );
}

function runDemo() {
  const n = 110;
  const start = new Date();
  start.setDate(start.getDate() - (n * 1.5));
  const dates = [];

  for (let index = 0; index < n; index += 1) {
    const date = new Date(start.getTime());
    date.setDate(start.getDate() + index);
    dates.push(date.toISOString().slice(0, 10));
  }

  const ratio = [];
  let value = 1.02;
  for (let index = 0; index < n; index += 1) {
    const drift = index < 55 ? -0.0012 : 0.0010;
    const noise = (Math.random() - 0.5) * 0.01;
    value = Math.max(0.7, value * (1 + drift + (noise * 0.2)));
    ratio.push(value);
  }

  const smoothing = Number(document.getElementById("smooth").value);
  const ratioSmooth = smoothing > 1 ? movingAverage(ratio, smoothing) : ratio.slice();
  const ratioMA = movingAverage(ratioSmooth, 20);

  makeChart(dates, ratioSmooth, ratioMA);
  renderTable(ALL_ETFS.map((item) => ({
    ticker: item.ticker,
    name: item.name,
    last: 100 + (Math.random() * 50),
    r1w: (Math.random() - 0.5) * 0.04,
    r1m: (Math.random() - 0.5) * 0.08,
    r3m: (Math.random() - 0.5) * 0.18
  })).sort((a, b) => a.ticker.localeCompare(b.ticker)));

  setBadge("warn", "Demo mode");
  setStatus("ok", "Demo data only. Run the updater script to replace this with real ETF history.", "CSV: demo");
}

function disableButtons(disabled) {
  document.getElementById("loadBtn").disabled = disabled;
  document.getElementById("demoBtn").disabled = disabled;
}

function init() {
  setBuildInfo();
  renderChecklist();

  document.getElementById("cycTickers").textContent = CYCLICAL.map((item) => item.ticker).join(", ");
  document.getElementById("defTickers").textContent = DEFENSIVE.map((item) => item.ticker).join(", ");
  document.getElementById("csvPath").value = CSV_PATH;

  document.getElementById("loadBtn").addEventListener("click", async () => {
    try {
      disableButtons(true);
      await runFromCsv();
    } catch (error) {
      console.error(error);
      setBadge("bad", "Error");
      setStatus("bad", String(error.message || error), "CSV: unavailable");
    } finally {
      disableButtons(false);
    }
  });

  document.getElementById("demoBtn").addEventListener("click", () => runDemo());

  runFromCsv().catch((error) => {
    console.error(error);
    setBadge("warn", "Waiting for CSV");
    setStatus("warn", "CSV not loaded yet. Showing demo data until the updater script has been run.", "CSV: missing");
    runDemo();
  });
}

window.addEventListener("load", init);
